spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #数据库驱动
    username: root
    password: 123456
    url: jdbc:mysql://192.168.100.235/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true #数据库语句打印出来
server:
  servlet:
    context-path: /sell
#  hibernate:
#    naming:
#      physical-strategy: com.XX.XX.common.MySQLUpperCaseStrategy
